openapi: 3.0.0
info:
  title: Customers and Devices
  version: 1.0.0
  description: Manage CRUD operations on customers and their devices
paths:
  /customers/{customerId}:
    get:
      operationId: getCustomer
      description: Retrieve customer data, with or without aggregated device data
      parameters:
        - &customerId
          in: path
          name: customerId
          required: true
          schema:
            type: string
        - in: query
          name: aggregateDevices
          required: false
          schema:
            type: boolean
            default: false
      responses:
        200:
          description: the customer data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
  /customers/{customerId}/address:
    put:
      operationId: updateCustomerAddress
      parameters:
        - *customerId
      requestBody:
        description: the new address
        content:
          application/json:
            schema:
              type: string
      responses:
        204:
          description: address updated
  /devices/{deviceCode}:
    get:
      operationId: getDevice
      parameters:
        - &deviceCode
          in: path
          name: deviceCode
          schema:
            type: string
          required: true
      responses:
        200:
          description: the retrieved device
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
  /devices/{deviceCode}/status:
    put:
      operationId: updateDeviceStatus
      parameters:
        - *deviceCode
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceStatus'
      responses:
        204:
          description: status updated
components:
  schemas:
    Customer:
      type: object
      required: [id, name, surname, taxCode, address]
      properties:
        id:
          type: string
          readOnly: true
        name:
          type: string
        surname:
          type: string
        taxCode:
          type: string
        address:
          type: string
        devices:
          type: array
          items:
            $ref: '#/components/schemas/Device'
    Device:
      type: object
      required: [code, status]
      properties:
        code:
          type: string
          format: uuid
        status:
          $ref: '#/components/schemas/DeviceStatus'
        customers:
          type: array
          maxLength: 2
          items:
            $ref: '#/components/schemas/Customer'
    DeviceStatus:
      type: string
      enum: [ACTIVE, INACTIVE, LOST]